Vagrant.configure(2) do |config|
  # config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  config.vm.define :svr01 do |server|
    ### determined specific IP.
    server.vm.network "private_network", ip: "192.168.33.81", auto_config: false
    ### hostname of server
    server.vm.hostname = 'gitlab-dev01'
    ### box setting
    server.vm.box = "bento/ubuntu-16.04"
    ### vm setting
    server.vm.provider "virtualbox" do |vb|
      ### name of virtualbox
      vb.name = "gitlab-dev01"
      ### spec define
      vb.customize ['modifyvm', :id,"--memory", 1024]
      vb.customize ['modifyvm', :id,"--natdnshostresolver1", "on"]
      vb.customize ['modifyvm', :id,"--natdnsproxy1", "on"]
    end
    ### bug fix
    server.vm.provision 'shell', inline: "ifconfig enp0s8 192.168.33.81"
    server.vm.provision 'shell', inline: "sed -i 's/exit\ 0/ifconfig\ enp0s8\ 192\.168\.33\.81/g' /etc/rc.local"
    server.vm.provision 'shell', inline: "echo 'exit 0' >> /etc/rc.local"
    server.vm.provision 'shell', inline: "chmod 644 /home/vagrant/.ssh/authorized_keys"

    ### settitng of synced_folder
    server.vm.synced_folder "../../", "/develop/gitlab-dev", \
      :create => true, \
      :owner  => 'vagrant', \
      :group  => 'vagrant', \
      :mount_options => ['dmode=755,fmode=755']

    server.vm.provision :shell, inline: "/bin/bash /develop/gitlab-dev/opsfiles/vagrant/provision.sh"
  end
end
